/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

/**
 *
 * @author csama
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btnLimpiarTextoOTP = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResultadoTextoCifradoOTP = new javax.swing.JTextArea();
        btnDescifrarTextoAtbash = new javax.swing.JButton();
        btnLimpiarTextoAtbash = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtTextoADescifrarAtbash = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtResultadoTextoDescifradoAtbash = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTextoACifrarOTP = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtClaveDeCifradoOTP = new javax.swing.JTextArea();
        btnCifrarTextoOTP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Texto cifrado:");

        btnLimpiarTextoOTP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiarTextoOTP.setText("Limpiar");
        btnLimpiarTextoOTP.setActionCommand("jButtonLimpiarOneTimePad");
        btnLimpiarTextoOTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarTextoOTPMouseClicked(evt);
            }
        });
        btnLimpiarTextoOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTextoOTPActionPerformed(evt);
            }
        });

        txtResultadoTextoCifradoOTP.setEditable(false);
        txtResultadoTextoCifradoOTP.setColumns(20);
        txtResultadoTextoCifradoOTP.setLineWrap(true);
        txtResultadoTextoCifradoOTP.setRows(5);
        jScrollPane3.setViewportView(txtResultadoTextoCifradoOTP);

        btnDescifrarTextoAtbash.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDescifrarTextoAtbash.setText("Descifrar texto por Atbash");
        btnDescifrarTextoAtbash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDescifrarTextoAtbashMouseClicked(evt);
            }
        });

        btnLimpiarTextoAtbash.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiarTextoAtbash.setText("Limpiar");
        btnLimpiarTextoAtbash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarTextoAtbashMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Texto a descifrar:");

        txtTextoADescifrarAtbash.setColumns(20);
        txtTextoADescifrarAtbash.setLineWrap(true);
        txtTextoADescifrarAtbash.setRows(5);
        txtTextoADescifrarAtbash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTextoADescifrarAtbashKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(txtTextoADescifrarAtbash);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Texto descifrado:");

        txtResultadoTextoDescifradoAtbash.setEditable(false);
        txtResultadoTextoDescifradoAtbash.setColumns(20);
        txtResultadoTextoDescifradoAtbash.setLineWrap(true);
        txtResultadoTextoDescifradoAtbash.setRows(5);
        jScrollPane5.setViewportView(txtResultadoTextoDescifradoAtbash);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cifrado por One-Time-Pad");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Descifrado por Atbash");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Texto a cifrar:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Clave de cifrado:");

        txtTextoACifrarOTP.setColumns(20);
        txtTextoACifrarOTP.setLineWrap(true);
        txtTextoACifrarOTP.setRows(5);
        txtTextoACifrarOTP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTextoACifrarOTPKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtTextoACifrarOTP);

        txtClaveDeCifradoOTP.setColumns(20);
        txtClaveDeCifradoOTP.setLineWrap(true);
        txtClaveDeCifradoOTP.setRows(5);
        txtClaveDeCifradoOTP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveDeCifradoOTPKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtClaveDeCifradoOTP);

        btnCifrarTextoOTP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCifrarTextoOTP.setText("Cifrar texto por OneTimePad");
        btnCifrarTextoOTP.setActionCommand("jButtonCifrarOneTimePad");
        btnCifrarTextoOTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCifrarTextoOTPMouseClicked(evt);
            }
        });
        btnCifrarTextoOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCifrarTextoOTPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(btnCifrarTextoOTP)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnLimpiarTextoAtbash))
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane4)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnLimpiarTextoOTP)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDescifrarTextoAtbash)
                .addGap(272, 272, 272))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCifrarTextoOTP)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnLimpiarTextoOTP)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDescifrarTextoAtbash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnLimpiarTextoAtbash)))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarTextoOTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarTextoOTPMouseClicked
        txtTextoACifrarOTP.setText("");
        txtClaveDeCifradoOTP.setText("");
        txtResultadoTextoCifradoOTP.setText("");
    }//GEN-LAST:event_btnLimpiarTextoOTPMouseClicked

    private void btnLimpiarTextoOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTextoOTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarTextoOTPActionPerformed

    private void btnDescifrarTextoAtbashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDescifrarTextoAtbashMouseClicked
        Atbash at = new Atbash();
        String texto = txtTextoADescifrarAtbash.getText();

        String resultado = at.descifrarTextoAtbash(texto);
        txtResultadoTextoDescifradoAtbash.setText(resultado);

    }//GEN-LAST:event_btnDescifrarTextoAtbashMouseClicked

    private void btnLimpiarTextoAtbashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarTextoAtbashMouseClicked
        txtTextoADescifrarAtbash.setText("");
        txtResultadoTextoDescifradoAtbash.setText("");
    }//GEN-LAST:event_btnLimpiarTextoAtbashMouseClicked

    private void txtTextoADescifrarAtbashKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTextoADescifrarAtbashKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;

        if(!(mayusculas || minusculas || espacio)){
            evt.consume();
        }
    }//GEN-LAST:event_txtTextoADescifrarAtbashKeyTyped

    private void txtTextoACifrarOTPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTextoACifrarOTPKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;

        if(!(mayusculas || minusculas || espacio)){
            evt.consume();
        }
    }//GEN-LAST:event_txtTextoACifrarOTPKeyTyped

    private void txtClaveDeCifradoOTPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveDeCifradoOTPKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;

        if(!(mayusculas || minusculas || espacio)){
            evt.consume();
        }
    }//GEN-LAST:event_txtClaveDeCifradoOTPKeyTyped

    private void btnCifrarTextoOTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCifrarTextoOTPMouseClicked
        OneTimePad otp = new OneTimePad();
        String texto = txtTextoACifrarOTP.getText();
        String clave = txtClaveDeCifradoOTP.getText();

        String resultado = otp.cifrarTextoOneTimePad(texto, clave);
        txtResultadoTextoCifradoOTP.setText(resultado);

    }//GEN-LAST:event_btnCifrarTextoOTPMouseClicked

    private void btnCifrarTextoOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCifrarTextoOTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCifrarTextoOTPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCifrarTextoOTP;
    private javax.swing.JButton btnDescifrarTextoAtbash;
    private javax.swing.JButton btnLimpiarTextoAtbash;
    private javax.swing.JButton btnLimpiarTextoOTP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea txtClaveDeCifradoOTP;
    private javax.swing.JTextArea txtResultadoTextoCifradoOTP;
    private javax.swing.JTextArea txtResultadoTextoDescifradoAtbash;
    private javax.swing.JTextArea txtTextoACifrarOTP;
    private javax.swing.JTextArea txtTextoADescifrarAtbash;
    // End of variables declaration//GEN-END:variables
}
